[build]
  publish = "static_deploy"
  command = "mkdir -p static_deploy && cp index.html static_deploy/ && cp -r static/* static_deploy/ 2>/dev/null || true"

[build.environment]
  # Remove Node.js requirement since this is a Python project
  # NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
